package main

var x86cc = map[string]string{
	"a":   "if above",
	"ae":  "if above or equal",
	"b":   "if below",
	"be":  "if below or equal",
	"c":   "if carry",
	"e":   "if equal",
	"g":   "if greater",
	"ge":  "if greater or equal",
	"l":   "if less",
	"le":  "if less or equal",
	"na":  "if not above",
	"nae": "if not above or equal",
	"nb":  "if not below",
	"nbe": "if not below or equal",
	"nc":  "if not carry",
	"ne":  "if not equal",
	"ng":  "if not greater",
	"nge": "if not greater or equal",
	"nl":  "if not less",
	"nle": "if not less or equal",
	"no":  "if not overflow",
	"ns":  "if not sign",
	"nz":  "if not zero",
	"np":  "if not parity",
	"npe": "if not parity even",
	"npo": "if not parity odd",
	"s":   "if sign",
	"z":   "if zero",
}
